#TODO use Clojure config
version: 2.1
aliases:
  cache:
    lein_cache: &LEIN_CACHE
      key: lein-{{ checksum "project.clj" }}
      paths:
        - ~/.lein
        - ~/.m2
    node_cache: &NODE_CACHE
      key: node-{{ checksum "/tmp/.node_version" }}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  containers:
    docker: &DEFAULT
      - image: jesiio/build-bus:latest
        environment:
          JVM_OPTS: -Xmx3200m
          DEBUG: 1
  commands:
    cancel_redundant: &CANCEL_REDUNDANT
      run:
        name: Check & Cancel Redundant Build
        command: 'cancel-redundant-builds.sh'
    submodule: &SUBMODULE
      run: git submodule update --init
jobs:
  build:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - restore_cache:
          <<: *NODE_CACHE
      - run: './bindle.sh lint'
      - save_cache:
          <<: *LEIN_CACHE
      - save_cache:
          <<: *NODE_CACHE
